// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCct1ZBDVrLz9UJ2TlOfSWKEodbBNPafzM',
    appId: '1:280342902159:web:efe6328b37a81fc56c47fa',
    messagingSenderId: '280342902159',
    projectId: 'blogp-acbdb',
    authDomain: 'blogp-acbdb.firebaseapp.com',
    storageBucket: 'blogp-acbdb.appspot.com',
    measurementId: 'G-04DWEB684X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACVnrxWYbilyd5s_6VLD2XAsjmKKBlb7Y',
    appId: '1:280342902159:android:ea957417265e480a6c47fa',
    messagingSenderId: '280342902159',
    projectId: 'blogp-acbdb',
    storageBucket: 'blogp-acbdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5LEnh-BLV9FkETxO2Ok_2aQ1QbS-E48U',
    appId: '1:280342902159:ios:9d0470183b8615aa6c47fa',
    messagingSenderId: '280342902159',
    projectId: 'blogp-acbdb',
    storageBucket: 'blogp-acbdb.appspot.com',
    iosClientId: '280342902159-hv1tuan1a162e9m3sbbamfmur6ngirsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5LEnh-BLV9FkETxO2Ok_2aQ1QbS-E48U',
    appId: '1:280342902159:ios:9d0470183b8615aa6c47fa',
    messagingSenderId: '280342902159',
    projectId: 'blogp-acbdb',
    storageBucket: 'blogp-acbdb.appspot.com',
    iosClientId: '280342902159-hv1tuan1a162e9m3sbbamfmur6ngirsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );
}
